import { Link } from "react-router-dom";
import { FileText, BookOpen, Atom, Download } from "lucide-react";

export default function MethodPage() {
  return (
    <div className="container py-10">
      <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="text-3xl font-bold">Generated Method: Amlodipine</h1>
          <p className="text-muted-foreground">HPLC – API Sample | Generated by LCForge AI (Demo)</p>
        </div>
        <div className="flex gap-2">
          <Link to="/literature" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-md border text-sm font-medium hover:bg-muted transition-colors">
            <BookOpen className="w-4 h-4" /> View Literature
          </Link>
          <Link to="/properties" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-md border text-sm font-medium hover:bg-muted transition-colors">
            <Atom className="w-4 h-4" /> View Properties
          </Link>
          <button disabled className="inline-flex items-center gap-1.5 px-4 py-2 rounded-md bg-muted text-muted-foreground text-sm font-medium cursor-not-allowed">
            <Download className="w-4 h-4" /> Export (Demo)
          </button>
        </div>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* HPLC Method */}
        <div className="card-science p-6">
          <h2 className="font-bold text-lg mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" /> HPLC Method Parameters
          </h2>
          <table className="w-full text-sm">
            <tbody className="divide-y">
              {[
                ["Column", "C18, 250 × 4.6 mm, 5 µm"],
                ["Mobile Phase A", "0.1% Formic Acid in Water"],
                ["Mobile Phase B", "Acetonitrile"],
                ["Buffer", "20 mM Ammonium Acetate, pH 4.5"],
                ["Flow Rate", "1.0 mL/min"],
                ["Injection Volume", "20 µL"],
                ["Column Temp", "30 °C"],
                ["Detection", "UV at 237 nm"],
                ["Run Time", "15 min"],
              ].map(([k, v]) => (
                <tr key={k}>
                  <td className="py-2 font-medium text-muted-foreground w-40">{k}</td>
                  <td className="py-2 font-mono text-sm">{v}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <h3 className="font-semibold mt-5 mb-2 text-sm">Gradient Table</h3>
          <table className="w-full text-sm border">
            <thead className="bg-muted">
              <tr>
                <th className="px-3 py-1.5 text-left font-medium">Time (min)</th>
                <th className="px-3 py-1.5 text-left font-medium">%A</th>
                <th className="px-3 py-1.5 text-left font-medium">%B</th>
              </tr>
            </thead>
            <tbody className="divide-y font-mono">
              {[["0", "90", "10"], ["5", "60", "40"], ["10", "30", "70"], ["12", "90", "10"], ["15", "90", "10"]].map(([t, a, b]) => (
                <tr key={t}>
                  <td className="px-3 py-1.5">{t}</td>
                  <td className="px-3 py-1.5">{a}</td>
                  <td className="px-3 py-1.5">{b}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* LC-MS Parameters */}
        <div className="card-science p-6">
          <h2 className="font-bold text-lg mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" /> LC-MS Parameters
          </h2>
          <table className="w-full text-sm">
            <tbody className="divide-y">
              {[
                ["Ionization Mode", "ESI Positive"],
                ["MRM Transition", "409.2 → 238.1"],
                ["Fragmentor Voltage", "120 V"],
                ["Collision Energy", "25 eV"],
                ["Source Temperature", "350 °C"],
                ["Gas Flow", "10 L/min"],
                ["Capillary Voltage", "3500 V"],
              ].map(([k, v]) => (
                <tr key={k}>
                  <td className="py-2 font-medium text-muted-foreground w-44">{k}</td>
                  <td className="py-2 font-mono text-sm">{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Analytical Quality */}
        <div className="card-science p-6 lg:col-span-2">
          <h2 className="font-bold text-lg mb-4">Analytical Quality by Design (QbD)</h2>
          <div className="grid sm:grid-cols-3 gap-6 text-sm">
            <div>
              <h3 className="font-semibold mb-2 text-primary">Critical Method Parameters</h3>
              <ul className="space-y-1 text-muted-foreground list-disc list-inside">
                <li>Mobile phase pH (±0.2)</li>
                <li>Column temperature (±2°C)</li>
                <li>Flow rate (±0.05 mL/min)</li>
                <li>Gradient slope</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2 text-primary">Critical Quality Attributes</h3>
              <ul className="space-y-1 text-muted-foreground list-disc list-inside">
                <li>Resolution &gt; 2.0</li>
                <li>Tailing factor 0.8–1.5</li>
                <li>%RSD &lt; 2.0</li>
                <li>Retention time stability</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-2 text-primary">System Suitability</h3>
              <ul className="space-y-1 text-muted-foreground list-disc list-inside">
                <li>Theoretical plates &gt; 2000</li>
                <li>Resolution ≥ 2.0</li>
                <li>Tailing ≤ 1.5</li>
                <li>%RSD ≤ 2.0 (n=5)</li>
              </ul>
            </div>
          </div>
          <p className="text-xs text-muted-foreground mt-4 p-3 rounded-md bg-muted">
            ℹ️ In production, this section would be generated by AI from literature + QbD models with full risk assessment matrices.
          </p>
        </div>
      </div>
    </div>
  );
}
